version: 2
updates:
  - package-ecosystem: "gradle"
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "[DEPENDABOT]"
    labels:
      - "Library Update"
    open-pull-requests-limit: 10