name: Main
'on':
  push:
    branches:
      - main
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Caching gradle
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Running unit tests
      - name: Unit tests
        run: ./gradlew clean testSandDebugUnitTest testDebugUnitTest

      # Publish test report
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
