name: Pull Request
'on':
  pull_request:
    branches:
      - main
jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew testSandDebugUnitTest
